### ISSUE TITLE
Hello,How to obtain the point cloud in your paper? 

### ISSUE THREAD

**Issue by AFESDTTM** [NOrangeeroli/SecondPose#1]
How to obtain the point cloud in your paper? Was it generated using code? If so, could you provide the code
![image](https://github.com/NOrangeeroli/SecondPose/assets/106895081/efcb94a1-7b8b-46f0-8760-56fa71bd04cc)

**Comment by NOrangeeroli** [comment]
Hi, it was generated by code. But the code has been cleaned up, it's rendered by pytorch3d, with the color calculated by joint pca.

**Comment by AFESDTTM** [comment]
OK，Thank you
