### ISSUE TITLE
 How to use dino to generate semantic features？

### ISSUE THREAD

**Issue by huiyang0613** [NOrangeeroli/SecondPose#2]
Thank you very much for the work, when I use the extractor_dino.py to generate semantic features, when I keep the parameters unchanged, I get the output feature is 1*1*3025*6528, but I see that the semantic feature in your vinet-dino file is bs*c*h*w, I want to know how this is converted?

**Comment by dj1367250510** [comment]
Hello, can I ask for some help from you?

**Comment by NOrangeeroli** [comment]
> Thank you very much for the work, when I use the extractor_dino.py to generate semantic features, when I keep the parameters unchanged, I get the output feature is 1_1_3025_6528, but I see that the semantic feature in your vinet-dino file is bs_c_h_w, I want to know how this is converted?

I think it is just permute the axis and resize the tensor. My code finally didn't use extractor_dino.py, but the extractor function in model/VI_Net_geodino.py to extract dino features. You can check the code there. :D
