### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by sseunghyuns** [NOrangeeroli/SecondPose#4]
Thank you for the excellent research! 

How long did it take to train on the NOCS dataset and the HouseCat6D dataset respectively? 
Also, could you share the training code for the HouseCat6D dataset?

**Comment by shangbuhuan13** [comment]
On a single 4090, it takes less than 1 day to train on NOCS (60 epochs).

**Comment by shangbuhuan13** [comment]
For HouseCat6D, we will release the code later. If you need to evaluate your model on HouseCat6D, you can also contact the author of HouseCat6D via the email address provided on their website guangyao.zhai@tum.de
He will provide you the training and evaluation scripts for HouseCat6D.

**Comment by sseunghyuns** [comment]
Thank you for your kind response.

**Comment by PANFEI-CHENG** [comment]
> On a single 4090, it takes less than 1 day to train on NOCS (60 epochs).
![微信图片_20241009192236](https://github.com/user-attachments/assets/13b4b7a2-7652-4e88-8bf8-6bce46305d04)


Hi, when I run train_geodino.py on my 4090, I find that the training time for one epoch is 73 minutes. I choose REAL275 dataset. Do you mean CAMERA25 when you say less than one day?
