### ISSUE TITLE
Missing detection results required for test_geodino

### ISSUE THREAD

**Issue by convolutionalJellyfish** [NOrangeeroli/SecondPose#6]
Hi, thank you so much for your great work! 

I am trying to recreate the results from your paper.
I saw in a different issue that I should add a soft link from `detection` to `segmentation_results` (downloaded from Self-DPDN), so I did so.
I could then run `data_preprocess.py` without error.
I have trained both the TS and R models separately until 60 epochs as per the README.

Now I am trying to run the command
```
python test_geodino.py --gpus 0 --test_epoch [YOUR EPOCH]
```
to check the results of my training.

However (after fixing some bugs to get the script to run), I don't get any results. All the printed values are 0.
After checking the code directly, it seems it is looking for:

https://github.com/NOrangeeroli/SecondPose/blob/f4b64941e46330a09a97cd00278a5f7675307a42/provider/dataset_category.py#L715

however this information doesn't exist in my `detection` folder, it looks like this:

```
$ ls data/detection
camera_test_category_dict.json  real_test_category_dict.json  test_trainedwithMask  test_trainedwoMask  train_trainedwoMask
```

(I noticed that both of the json files are empty, is this normal?
After looking at the code, I am guessing it is empty because it is searching for `detection/dataset/results*pkl` but not finding it.)

Could you please upload your `detection` folder with the `detection/dataset/results*pkl` files?

Thanks for your time!!!

**Comment by AFESDTTM** [comment]
你好，你解决了吗

**Comment by ran894694447** [comment]
Hi, you can download it from [DualPoseNet](https://github.com/Gorilla-Lab-SCUT/DualPoseNet?tab=readme-ov-file)

**Comment by AFESDTTM** [comment]
> Hi, you can download it from [DualPoseNet](https://github.com/Gorilla-Lab-SCUT/DualPoseNet?tab=readme-ov-file)

我是去下载这里面的测试的代码吗

**Comment by convolutionalJellyfish** [comment]
> Hi, you can download it from [DualPoseNet](https://github.com/Gorilla-Lab-SCUT/DualPoseNet?tab=readme-ov-file)

Thank you, it works!!

**Comment by sdu-huanhq** [comment]
> > Hi, you can download it from [DualPoseNet](https://github.com/Gorilla-Lab-SCUT/DualPoseNet?tab=readme-ov-file)
> 
> Thank you, it works!!

Hello, how do you get the two files: camera_test_category_dict.json and real_test_category_dict.json?
